-- MySQL Script generated by MySQL Workbench
-- Tue Oct 11 09:21:21 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema balay4rentdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema balay4rentdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `balay4rentdb` DEFAULT CHARACTER SET utf8 ;
USE `balay4rentdb` ;

-- -----------------------------------------------------
-- Table `balay4rentdb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `balay4rentdb`.`users` ;

CREATE TABLE IF NOT EXISTS `balay4rentdb`.`users` (
  `user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `contact_info` VARCHAR(20) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `user_role` ENUM('tenant', 'home_owner') NOT NULL,
  `createdAt` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL,
  PRIMARY KEY (`user_id`));


-- -----------------------------------------------------
-- Table `balay4rentdb`.`amenities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `balay4rentdb`.`amenities` ;

CREATE TABLE IF NOT EXISTS `balay4rentdb`.`amenities` (
  `amenities_id` INT NOT NULL,
  `bed_type` VARCHAR(50) NOT NULL DEFAULT 0,
  `electricity_meter` TINYINT NOT NULL DEFAULT 0,
  `water_meter` TINYINT NOT NULL DEFAULT 0,
  `own_cr` TINYINT NOT NULL DEFAULT 0,
  `with_foam` TINYINT NOT NULL DEFAULT 0,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL,
  PRIMARY KEY (`amenities_id`));


-- -----------------------------------------------------
-- Table `balay4rentdb`.`rentable`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `balay4rentdb`.`rentable` ;

CREATE TABLE IF NOT EXISTS `balay4rentdb`.`rentable` (
  `rentable_id` INT NOT NULL AUTO_INCREMENT,
  `amenities_id` INT NOT NULL,
  `rentable_name` VARCHAR(100) NOT NULL DEFAULT 'N/A',
  `rentable_location` VARCHAR(255) NOT NULL DEFAULT 'N/A',
  `reservation_price` FLOAT NOT NULL,
  `description` TEXT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NULL,
  PRIMARY KEY (`rentable_id`),
  INDEX `fk_rentable_amenities1_idx` (`amenities_id` ASC) VISIBLE,
  CONSTRAINT `fk_rentable_amenities1`
    FOREIGN KEY (`amenities_id`)
    REFERENCES `balay4rentdb`.`amenities` (`amenities_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `balay4rentdb`.`rent_transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `balay4rentdb`.`rent_transaction` ;

CREATE TABLE IF NOT EXISTS `balay4rentdb`.`rent_transaction` (
  `rent_transaction_id` INT NOT NULL,
  `owner_id` INT UNSIGNED NOT NULL,
  `rentable_id` INT NOT NULL,
  `relocation_date` DATE NOT NULL,
  `rent_transaction_status` ENUM('pending', 'ongoing', 'approved') NOT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `closedAt` TIMESTAMP NULL,
  PRIMARY KEY (`rent_transaction_id`),
  INDEX `fk_rent_transaction_users_idx` (`owner_id` ASC) VISIBLE,
  INDEX `fk_rent_transaction_rentable1_idx` (`rentable_id` ASC) VISIBLE,
  CONSTRAINT `fk_rent_transaction_users`
    FOREIGN KEY (`owner_id`)
    REFERENCES `balay4rentdb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rent_transaction_rentable1`
    FOREIGN KEY (`rentable_id`)
    REFERENCES `balay4rentdb`.`rentable` (`rentable_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
